'use strict';

var assert = require('assert');
var test = require('node:test');
var AssStyle = require('../../tizen-web-vlc/js/ass-style.js');

/* The reporter's file from the .ass styling issue, trimmed to the parts
 * that matter.  Style: Default carries an opaque-white PrimaryColour and
 * the dialogue switches to yellow mid-cue with {\c&H00FFFF&}. */
var REPORTER_ASS = [
    '[Script Info]',
    '; Script generated by SubtitleKit',
    'Title: Untitled',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'PlayResX: 384',
    'PlayResY: 288',
    'ScaledBorderAndShadow: yes',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour,' +
        ' BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing,' +
        ' Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    'Style: Default,Arial,16,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,' +
        '100,100,0,0,1,2,2,2,10,10,10,1',
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
    "Dialogue: 0,0:01:21.66,0:01:26.71,Default,,0,0,0,,I should've known that you would" +
        '\\Nbe here, Professor McGonagall.\\N{\\c&H00FFFF&}Tôi biết là bà sẽ ở đây mà' +
        '\\NGiáo sư McGonagall.{\\c}'
].join('\n');

var REPORTER_TEXT = "I should've known that you would\\Nbe here, Professor McGonagall." +
    '\\N{\\c&H00FFFF&}Tôi biết là bà sẽ ở đây mà\\NGiáo sư McGonagall.{\\c}';

/* ── Colour decoding ─────────────────────────────────────────────────── */

test('decodeColour reads ASS colours as BGR, not RGB', function () {
    // &H00FFFF& → BB=00 GG=FF RR=FF → yellow.  Read as RGB it would be cyan.
    var c = AssStyle.decodeColour('&H00FFFF&');
    assert.strictEqual(c.css, '#ffff00');
    assert.strictEqual(c.r, 255);
    assert.strictEqual(c.g, 255);
    assert.strictEqual(c.b, 0);
});

test('decodeColour handles the 8-digit AABBGGRR style spelling', function () {
    assert.strictEqual(AssStyle.decodeColour('&H00FFFFFF').css, '#ffffff'); // opaque white
    assert.strictEqual(AssStyle.decodeColour('&H000000FF').css, '#ff0000'); // opaque red
    assert.strictEqual(AssStyle.decodeColour('&H00FF0000').css, '#0000ff'); // opaque blue
});

test('decodeColour zero-pads short forms', function () {
    assert.strictEqual(AssStyle.decodeColour('&HFF&').css, '#ff0000');
    assert.strictEqual(AssStyle.decodeColour('&H0&').css, '#000000');
});

test('decodeColour treats the alpha byte as transparency', function () {
    // AA=00 is opaque, AA=FF is invisible — inverted from CSS alpha.
    assert.strictEqual(AssStyle.decodeColour('&H00FFFFFF').a, 1);
    var half = AssStyle.decodeColour('&H80FFFFFF');
    assert.ok(half.a > 0.49 && half.a < 0.51, 'AA=80 → ~0.5 opacity, got ' + half.a);
    assert.match(half.css, /^rgba\(255,255,255,0\.5/);
});

test('decodeColour rejects junk', function () {
    assert.strictEqual(AssStyle.decodeColour(''), null);
    assert.strictEqual(AssStyle.decodeColour(null), null);
    assert.strictEqual(AssStyle.decodeColour('yellow'), null);
});

/* ── Style table ─────────────────────────────────────────────────────── */

test('parseStyles reads PrimaryColour off the Format: column order', function () {
    var t = AssStyle.parseStyles(REPORTER_ASS);
    assert.strictEqual(t.count, 1);
    var d = t.get('Default');
    assert.strictEqual(d.name, 'Default');
    assert.strictEqual(d.colour.css, '#ffffff');
    assert.strictEqual(d.bold, false);
    assert.strictEqual(d.italic, false);
});

test('parseStyles handles legacy [V4 Styles] with a different column order', function () {
    var ssa = [
        '[V4 Styles]',
        'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour,' +
            ' TertiaryColour, BackColour, Bold, Italic',
        'Style: Alt,Arial,20,&H0000FF00,&H00000000,&H00000000,&H00000000,-1,-1'
    ].join('\n');
    var s = AssStyle.parseStyles(ssa).get('Alt');
    assert.strictEqual(s.colour.css, '#00ff00');
    assert.strictEqual(s.bold, true);      // SSA spells "on" as -1
    assert.strictEqual(s.italic, true);
});

test('parseStyles lookup is case-insensitive and falls back to Default', function () {
    var t = AssStyle.parseStyles(REPORTER_ASS);
    assert.strictEqual(t.get('default').name, 'Default');
    assert.strictEqual(t.get('DEFAULT').name, 'Default');
    assert.strictEqual(t.get('NoSuchStyle').name, 'Default');   // fallback
    assert.strictEqual(t.get('').name, 'Default');
});

test('parseStyles ignores Style: lines outside the styles section', function () {
    var t = AssStyle.parseStyles('[Events]\nStyle: Bogus,Arial,16,&H000000FF');
    assert.strictEqual(t.count, 0);
    assert.strictEqual(t.get('Bogus'), null);
});

/* ── The reported bug ────────────────────────────────────────────────── */

test("the reporter's cue keeps its yellow second language", function () {
    var f = AssStyle.forFile(REPORTER_ASS);
    var runs = f.runs(REPORTER_TEXT, 'Default');

    assert.strictEqual(runs.length, 2, 'expected a white run then a yellow one');

    assert.strictEqual(runs[0].colour, '#ffffff');            // style PrimaryColour
    assert.match(runs[0].text, /I should've known/);
    assert.match(runs[0].text, /Professor McGonagall\.\n$/);  // \N became a newline

    assert.strictEqual(runs[1].colour, '#ffff00');            // ← the fix
    assert.strictEqual(runs[1].text, 'Tôi biết là bà sẽ ở đây mà\nGiáo sư McGonagall.');
});

test("plainText matches what the old strip pipeline produced", function () {
    // Regression guard: the visible characters must not change, only colour.
    var legacy = REPORTER_TEXT
        .replace(/\{[^}]*\}/g, '')
        .replace(/\\N/gi, '\n')
        .replace(/\\h/gi, ' ')
        .replace(/<[^>]+>/g, '')
        .trim();

    var runs = AssStyle.forFile(REPORTER_ASS).runs(REPORTER_TEXT, 'Default');
    assert.strictEqual(AssStyle.plainText(runs), legacy);
});

/* ── Inline overrides ────────────────────────────────────────────────── */

test('inline \\c and \\1c both set the primary colour', function () {
    assert.strictEqual(AssStyle.toRuns('{\\c&H0000FF&}red', null)[0].colour, '#ff0000');
    assert.strictEqual(AssStyle.toRuns('{\\1c&H0000FF&}red', null)[0].colour, '#ff0000');
});

test('bold / italic / underline / strikeout toggle on and off', function () {
    var runs = AssStyle.toRuns('plain{\\b1}bold{\\b0}{\\i1}it{\\i0}{\\u1}un{\\u0}{\\s1}st', null);
    var byText = {};
    runs.forEach(function (r) { byText[r.text] = r; });

    assert.strictEqual(byText.plain.bold, false);
    assert.strictEqual(byText.bold.bold, true);
    assert.strictEqual(byText.it.italic, true);
    assert.strictEqual(byText.un.underline, true);
    assert.strictEqual(byText.st.strikeout, true);
    assert.strictEqual(byText.it.bold, false, '\\b0 should have cleared bold');
});

test('\\b accepts a font weight, 600+ reads as bold', function () {
    assert.strictEqual(AssStyle.toRuns('{\\b700}x', null)[0].bold, true);
    assert.strictEqual(AssStyle.toRuns('{\\b400}x', null)[0].bold, false);
    assert.strictEqual(AssStyle.toRuns('{\\b0}x', null)[0].bold, false);
});

test('\\r resets to the dialogue style', function () {
    var style = { colour: AssStyle.decodeColour('&H00FFFFFF'), bold: false };
    var runs = AssStyle.toRuns('{\\c&H0000FF&\\b1}red bold{\\r}back to style', style);
    assert.strictEqual(runs[0].colour, '#ff0000');
    assert.strictEqual(runs[0].bold, true);
    assert.strictEqual(runs[1].colour, '#ffffff');
    assert.strictEqual(runs[1].bold, false);
});

test('\\rNamedStyle resets to that style when the table is known', function () {
    var ass = REPORTER_ASS.replace(
        '[Events]',
        'Style: Yellow,Arial,16,&H0000FFFF,&H0,&H0,&H0,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n[Events]'
    );
    var runs = AssStyle.forFile(ass).runs('{\\c&H0000FF&}red{\\rYellow}yellow', 'Default');
    assert.strictEqual(runs[0].colour, '#ff0000');
    assert.strictEqual(runs[1].colour, '#ffff00');
});

test('several tags in one block all apply', function () {
    var r = AssStyle.toRuns('{\\c&H00FFFF&\\b1\\i1}styled', null)[0];
    assert.strictEqual(r.colour, '#ffff00');
    assert.strictEqual(r.bold, true);
    assert.strictEqual(r.italic, true);
});

test('\\alpha and \\1a change opacity without losing the colour', function () {
    var r = AssStyle.toRuns('{\\c&H0000FF&\\alpha&H80&}faded', null)[0];
    assert.match(r.colour, /^rgba\(255,0,0,0\.5/);
});

/* ── Tags we deliberately don't draw ─────────────────────────────────── */

test('positioning and timing tags are dropped without leaking arguments', function () {
    var cases = [
        '{\\pos(320,240)}text',
        '{\\an8}text',
        '{\\a6}text',
        '{\\fs28}text',
        '{\\fn Comic Sans MS}text',
        '{\\move(0,0,100,100)}text',
        '{\\t(0,500,\\fs30)}text',
        '{\\fad(200,200)}text',
        '{\\clip(0,0,10,10)}text',
        '{\\k50}text',
        '{\\3c&H000000&}text',
        '{\\4c&H000000&}text',
        '{\\bord2}text',
        '{\\shad3}text',
        '{\\blur1.5}text',
        '{\\frz30}text',
        '{\\fscx120\\fscy120}text',
        '{\\fsp2}text',
        '{\\q2}text'
    ];
    cases.forEach(function (c) {
        var runs = AssStyle.toRuns(c, null);
        assert.strictEqual(AssStyle.plainText(runs), 'text',
            c + ' should render exactly "text"');
    });
});

test('prefix collisions resolve to the longer tag', function () {
    // \bord must not read as \b, \iclip as \i, \shad as \s, \pos as \p,
    // \clip as \c, \alpha as \a.
    assert.strictEqual(AssStyle.toRuns('{\\bord2}x', null)[0].bold, false);
    assert.strictEqual(AssStyle.toRuns('{\\iclip(1,2,3,4)}x', null)[0].italic, false);
    assert.strictEqual(AssStyle.toRuns('{\\shad2}x', null)[0].strikeout, false);
    assert.strictEqual(AssStyle.toRuns('{\\clip(0,0,9,9)}x', null)[0].colour, null);
    assert.strictEqual(AssStyle.plainText(AssStyle.toRuns('{\\pos(1,2)}x', null)), 'x');
});

test('vector drawing commands are suppressed, not painted as text', function () {
    // Without \p handling the coordinate soup renders as visible junk.
    var runs = AssStyle.toRuns('{\\p1}m 0 0 l 100 0 100 100 0 100{\\p0}', null);
    assert.strictEqual(AssStyle.plainText(runs), '');

    var mixed = AssStyle.toRuns('real{\\p1}m 0 0 l 5 5{\\p0}more', null);
    assert.strictEqual(AssStyle.plainText(mixed), 'realmore');
});

test('{comment} blocks with no backslash disappear', function () {
    assert.strictEqual(AssStyle.plainText(AssStyle.toRuns('{these are notes}shown', null)),
                       'shown');
});

/* ── Text escapes and edge cases ─────────────────────────────────────── */

test('\\N, \\n and \\h are unescaped', function () {
    assert.strictEqual(AssStyle.plainText(AssStyle.toRuns('a\\Nb', null)), 'a\nb');
    assert.strictEqual(AssStyle.plainText(AssStyle.toRuns('a\\nb', null)), 'a\nb');
    // \h is ASS's *hard* space: U+00A0, so the overlay won't wrap there.
    // The old strip pipeline flattened it to a plain space and could break
    // a line mid-phrase.
    assert.strictEqual(AssStyle.toRuns('a\\hb', null)[0].text, 'a\u00a0b');
});

test('stray HTML is stripped, as the old pipeline did', function () {
    // Hand-converted SRT→ASS files sometimes keep <i> tags; they must not
    // become visible text now that runs bypass showSubtitleText's sanitiser.
    assert.strictEqual(
        AssStyle.plainText(AssStyle.toRuns('<i>leaning</i> text', null)),
        'leaning text');
    assert.strictEqual(
        AssStyle.plainText(AssStyle.toRuns('{\\c&H00FFFF&}<b>bold</b>', null)),
        'bold');
});

test('an unmatched { renders literally rather than eating the line', function () {
    var runs = AssStyle.toRuns('visible {\\c&H0000FF& and no close brace', null);
    assert.match(AssStyle.plainText(runs), /visible/);
    assert.match(AssStyle.plainText(runs), /no close brace/);
});

test('adjacent runs with identical appearance are merged', function () {
    var runs = AssStyle.toRuns('one{\\b0}two{\\b0}three', null);
    assert.strictEqual(runs.length, 1);
    assert.strictEqual(runs[0].text, 'onetwothree');
});

test('empty and tag-only text produce no runs', function () {
    assert.deepStrictEqual(AssStyle.toRuns('', null), []);
    assert.deepStrictEqual(AssStyle.toRuns('{\\an8}', null), []);
    assert.strictEqual(AssStyle.plainText([]), '');
    assert.strictEqual(AssStyle.plainText(null), '');
});

test('isPlain spots run lists that need no spans', function () {
    assert.strictEqual(AssStyle.isPlain(AssStyle.toRuns('nothing special', null)), true);
    assert.strictEqual(AssStyle.isPlain(AssStyle.toRuns('{\\an8}moved only', null)), true);
    assert.strictEqual(AssStyle.isPlain(AssStyle.toRuns('{\\c&H00FFFF&}yellow', null)), false);
    assert.strictEqual(AssStyle.isPlain(AssStyle.toRuns('{\\b1}bold', null)), false);
    assert.strictEqual(AssStyle.isPlain(null), true);
    assert.strictEqual(AssStyle.isPlain([]), true);
});

test('a style with no colour leaves runs uncoloured so CSS keeps control', function () {
    var runs = AssStyle.toRuns('plain text', null);
    assert.strictEqual(runs[0].colour, null);
    assert.strictEqual(AssStyle.isPlain(runs), true);
});
